apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitlab-eventsource
  namespace: argo
  labels:
    app: demo-coding-agent
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  gitlab:
    commentWebhook:
      projectID: "74245624"
      webhook:
        endpoint: /gitlab
        port: "12000"
        method: POST
      events:
        - NoteEvents
      accessToken:
        name: demo-coding-agent-gitlab-secret
        key: token
      # secretToken:
      #   name: demo-coding-agent-gitlab-secret
      #   key: webhook-secret
      gitlabBaseURL: https://gitlab.com