apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitlab-eventsource
  namespace: argo
  labels:
    app: demo-coding-agent
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  gitlab:
    gitlab-webhook:
      port: 12000
      endpoint: /gitlab
      gitlabBaseURL: https://gitlab.com
      events:
        - "note"
      accessToken:
        name: demo-coding-agent-gitlab-secret
        key: token
      secretToken:
        name: demo-coding-agent-gitlab-secret
        key: webhook-secret