apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitlab-eventsource
  namespace: argo
  labels:
    app: demo-coding-agent
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  gitlab:
    commentWebhook:
      projectID: "74245624"
      webhook:
        endpoint: /gitlab
        port: "12000"
        method: POST
        url: http://gitlab-eventsource-eventsource-svc.argo.svc.cluster.local:12000/gitlab
      events:
        - CommentEvents
      accessToken:
        name: demo-coding-agent-gitlab-secret
        key: token
      gitlabBaseURL: https://gitlab.com