apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: slack-eventsource
spec:
  template:
    serviceAccountName: argo-events-sa
  slack-socketmode:
    type: custom
    container:
      image: registry.gitlab.com/littlewhywhat/slackbot-eventsource:latest
      env:
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: demo-coding-agent-slack-secrets
              key: app-token
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: demo-coding-agent-slack-secrets
              key: bot-token