apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: slack-eventsource
  namespace: argo
  labels:
    app: demo-coding-agent
spec:
  service:
    ports:
    - port: 13000
      targetPort: 13000
  webhook:
    slackMentions:
      endpoint: /slack
      port: "13000"
      method: POST
