apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gitlab-comment-workflow-template
  namespace: argo
  labels:
    app: demo-coding-agent
spec:
  arguments:
    parameters:
      - name: comment
      - name: project-id
      - name: merge-request-id
      - name: full-payload
      - name: repo-url
        value: "https://gitlab.com/littlewhywhat/demo-tanurkod.git"
  entrypoint: debug-and-process
  templates:
    - name: debug-and-process
      dag:
        tasks:
          - name: debug-payload
            template: debug-payload-step
          - name: clone-repo
            template: clone-repository
          - name: process-comment
            template: gitlab-comment-handler
            dependencies: [debug-payload, clone-repo]
    
    - name: debug-payload-step
      container:
        image: alpine:latest
        command: [sh]
        args:
          - -c
          - |
            apk add --no-cache jq
            echo "FULL PAYLOAD:"
            echo '{{workflow.parameters.full-payload}}' | jq .
            echo "======================================"
            echo "EXTRACTED VALUES:"
            echo "COMMENT: {{workflow.parameters.comment}}"
            echo "PROJECT_ID: {{workflow.parameters.project-id}}"
            echo "MERGE_REQUEST_ID: {{workflow.parameters.merge-request-id}}"
    
    - name: clone-repository
      container:
        image: alpine/git:latest
        workingDir: /workspace
        command: [sh]
        args:
          - -c
          - |
            echo "Cloning repository: {{workflow.parameters.repo-url}}"
            git clone {{workflow.parameters.repo-url}} .
            echo "Repository cloned successfully"
            ls -la
        env:
          - name: GITLAB_TOKEN
            valueFrom:
              secretKeyRef:
                name: demo-coding-agent-workflow-secrets
                key: gitlab-token
        volumeMounts:
          - name: workspace
            mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir:
            sizeLimit: 1Gi
    
    - name: gitlab-comment-handler
      container:
        image: registry.gitlab.com/littlewhywhat/demo-tanurkod:latest
        imagePullPolicy: Always
        workingDir: /workspace
        env:
          - name: COMMENT
            value: "{{workflow.parameters.comment}}"
          - name: PROJECT_ID
            value: "{{workflow.parameters.project-id}}"
          - name: MERGE_REQUEST_ID
            value: "{{workflow.parameters.merge-request-id}}"
          - name: GITLAB_TOKEN
            valueFrom:
              secretKeyRef:
                name: demo-coding-agent-workflow-secrets
                key: gitlab-token
          - name: CURSOR_TOKEN
            valueFrom:
              secretKeyRef:
                name: demo-coding-agent-workflow-secrets
                key: cursor-token
        volumeMounts:
          - name: workspace
            mountPath: /workspace
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
        - name: workspace
          emptyDir:
            sizeLimit: 1Gi
  imagePullSecrets:
    - name: demo-coding-agent-gitlab-registry
